version: '3.5'

services:

  database:
    image: 'postgres:15-alpine'
    container_name: database
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=renty
    restart: always
    networks:
      - renty-backend

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - database
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://database:5432/renty
      - --username=${POSTGRES_USER:-postgres}
      - --password=${POSTGRES_PASSWORD:-postgres}
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - renty-backend

volumes:
  db-data:
    name: db-data

networks:
  renty-backend: {}