spring:
  jpa:
    show-sql: true
    database: postgresql

  datasource:
    url: jdbc:postgresql://localhost:5434/renty
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  liquibase:
    change-log: migrations/master.xml

springdoc:
  swagger-ui:
    path: '/swagger-ui'

server:
  port: ${SERVER_PORT:8090}