spring:
  jpa:
    show-sql: true
    database: postgresql

  datasource:
    url: jdbc:postgresql://localhost:5434/renty
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

springdoc:
  swagger-ui:
    path: '/swagger-ui'