apiVersion: apps/v1
kind: Deployment
metadata:
  name: renty-api-deployment
  labels:
    service: renty-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: renty-api
  template:
    metadata:
      labels:
        service: renty-api
    spec:
      containers:
        - name: renty-api
          image: ghcr.io/sevolchenko/renty/server:latest
          ports:
            - containerPort: 8080
